<h4>Name?</h4>
Sara Hayden

<h4>Year & Major?</h4>
2012 (the year of The Apocalypse?!); intended Chinese and Environmental Economics and Policy majors

<h4>How many semesters have you been in Theatre Rice?</h4>
This is my first!

<h4>What kind of stuff do you do for fun?</h4>
Just LIVING is fun!  To maximize the most of my living hours, I enjoy seeking quirky, charming things-ya' know...eating raspberries and olives off my fingertips, flying kites, dancing with fairies in the dew, and pouring milk in cereal are among my primary past times.  When I'm not doing those things, my roommate and I are cosmetics-obsessed.  We produce and sell delicious cosmetics.  Our signature product is a luscious lip balm that comes in three tasty flavors: Blush 'n Bloom, Kiss Me Cream, and Fruit Orgy.  I love writing (both for the Daily Cal and for pleasure, though they usually go hand in hand), attempting different forms of dance (belly dancing and swing dancing are my current interests) traveling, hanging out in the mountains or on an ocean, teaching, learning, eating good food, talking to fascinating people.  I like to try new things EVERY DAY!!    

<h4>If you could have any superpower, what would it be?  Why?</h4>
I would swim through air.  "Why not simply fly?" you may ask.  Well, whenever I have a flying dream, my propelling motion is generated by swimming actions, generally like the breast stroke.  I do not have wings, or a rocket pack.  Just me, paddling through the air.  This extraordinary skill has allowed me to fly over mountains in India, inside sunny aviaries, and save the Hope Diamond when it was suspended in midair and I was a witch.  In my dreams, of course.   

<h4>What would your superhero name be?</h4>
Sara the Soaring Sorceress.  Fear me, revere me, embrace me!

<h4>What attracted you to Theatre Rice?</h4>
The opportunity to be silly!  And meet cool people, celebrate diversity, and produce great art for the community.

<h4>What would you say is your favorite movie?</h4>
Amelie.  Have you seen it?  DO!  It's got incredible heart.  The character of the titular name has taught me how to live.  Her appreciation for all the small things in life and ability to find joy in others' joys is an extraordinary gift.  It's a simple recipe for living well.  Plus, it's absolutely gorgeous artistically and it appeals to my Francophilia.   

<h4>If you could be any common household electrical appliance, what would it be?  Why?</h4>
Ix-nay on the laundry drier.  I've heard too many horror stories about people's cats taking an accidental spin in them.  Also, no kitchen ovens (Hansel and Gretel, any one?)
<br>
So my answer would be...a toaster oven.  I want to warm your heart and soul the same way a hot, buttery piece of cinnamon and sugar toast can on a lazy weekend.  Mmmm...  

<h4>What was the last song you had stuck in your head?</h4>
"Beautiful Boy" from John Lennon and Yoko Ono's Double Fantasy.  Had you seen me moments ago on lower Sproul, you could have heard me trilly whistling or humming it to myself, or perhaps the poor people who didn't actually have ear buds in their ears.  De facto serenading.  Yeeeesss! 

<h4>What's your favorite type of food?</h4>
Oh man.  I have to pick just one??  Not possible.  I do enjoy juicy tangerines and the fizzy spray of a clementine that refreshingly scents the room.  Treacle pudding.  Sticky rice and mango.  Wow.  I must have a severe sweets craving as I'm writing this.  Any sort of Asian food, though dim sum and hot tea (of any sort!) do wonders for my happiness score.

<h4>Name a performer you admire.  Why did you choose him/her?</h4>
Audrey Hepburn.  The woman is the epitome of class.  She was hot stuff without sacrificing her elegance and femininity.  She avoided scandal and supported charity.  See my blog post for more on this: http://blog.dailycal.org/arts/2009/02/post-516/
<br>
There should definitely be more artists like her.

<h4>Finally, sum yourself up in one word.</h4>
HUMAN.

